[package]
name = "term-clipboard"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
drop_guard = "0.3.0"
eyre = "0.6.12"
libc = "0.2.182"
regex = "1.12.3"
thiserror = "2.0.18"
